version: '3.4'

services:
  tigerhackshelloworldbackend:
    image: ${DOCKER_REGISTRY-}tigerhackshelloworldbackend
    ports:
        - "32771:80"
    env_file:
        - settings.env
        - .env
    build:
      context: .
      dockerfile: TigerHacksHelloWorldBackend/Dockerfile

  database:
    image: "postgres:14.1-alpine"
    container_name: helloworld-data
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    volumes:
      - hello_world_database:/var/lib/postgresql/data/

  datbase_initializer:
    build:
      context: ../Python
      dockerfile: Dockerfile.Database
    env_file:
      - .env
    depends_on:
      - database

volumes:
  hello_world_database:
